services:
    - docker

before_script:
    - echo 'hi from before_script'
#    - cd src
#    - echo -e "APP_NAME=${APP_NAME}\nAPP_ENV=${APP_ENV}\nAPP_KEY=${APP_KEY}\nAPP_URL=${APP_URL}\nAPP_TIMEZONE=${APP_TIMEZONE}\nLOG_CHANNEL=${LOG_CHANNEL}\nDB_CONNECTION=${DB_CONNECTION}\nDB_HOST=${DB_HOST}\nDB_PORT=${DB_PORT}\nDB_DATABASE=${DB_DATABASE}\nDB_USERNAME=${DB_USERNAME}\nDB_PASSWORD=${DB_PASSWORD}\nCACHE_DRIVER=${CACHE_DRIVER}\nQUEUE_CONNECTION=${QUEUE_CONNECTION}\n" > .env
#    - docker-compose up -d
#    - docker exec -it api php artisan migrate --seed
script:
    - echo 'hi from script'
#    - docker exec -it api vendor/bin/phpunit
#    - docker exec -it api vendor/bin/php-cs-fixer fix .

after_success:
    - echo 'building images'

deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
        branch: master
