services:
- docker
addons:
  ssh_known_hosts: ivan-todorovic.com
before_script:
- cd src
- echo -e "APP_NAME=${APP_NAME}\nAPP_ENV=${APP_ENV}\nAPP_KEY=${APP_KEY}\nAPP_URL=${APP_URL}\nAPP_TIMEZONE=${APP_TIMEZONE}\nLOG_CHANNEL=${LOG_CHANNEL}\nDB_CONNECTION=${DB_CONNECTION}\nDB_HOST=${DB_HOST}\nDB_PORT=${DB_PORT}\nDB_DATABASE=${DB_DATABASE}\nDB_USERNAME=${DB_USERNAME}\nDB_PASSWORD=${DB_PASSWORD}\nCACHE_DRIVER=${CACHE_DRIVER}\nQUEUE_CONNECTION=${QUEUE_CONNECTION}\n" > .env
- docker-compose up -d
- docker exec -it api php artisan migrate --seed
before_install:
- cd ..
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
script:
- docker exec -it api vendor/bin/phpunit
- docker exec -it api vendor/bin/php-cs-fixer fix .
deploy:
  provider: script
  script: bash ../scripts/deploy.sh
  on:
    branch: master
