services:
    - docker

jobs:
    include:
        - stage: test
          before_script:
              - echo "hi from before_script"
          script:
              - echo "hi from script itself"
        - stage: deploy
          if: branch=master
          script:
              - echo "hi from deploy script!"
